name: Tests
on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        images: ["nightly-2021-02-25-dev"]
    steps:
      - name: Install act
        run: |
          curl -s https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash
          echo "-P ubuntu-latest=catthehacker/ubuntu:act-latest" >> ~/.actrc
          echo "-P ubuntu-20.04=catthehacker/ubuntu:act-20.04" >> ~/.actrc
          echo "-P ubuntu-18.04=catthehacker/ubuntu:act-18.04" >> ~/.actrc
          echo "ubuntu-16.04=catthehacker/ubuntu:act-16.04" >> ~/.actrc

      - uses: actions/checkout@v2
      - name: Check version
        run: |
          which act
          act --version
          act -W tests/test.yml
